### ISSUE TITLE
is the ctc implementation gpu runnable?

### ISSUE THREAD

**Issue by mineshmathew** [rakeshvar/rnn_ctc#14]
@rakeshvar  I was wondering if this ctc implementation is gpu runnable.  Do you know if there are any such implementations in Theano/Keras. Except for warp_ctc in Torch I could not find any such implementations which run on GPUUs

**Comment by rakeshvar** [comment]
Theano's scan function, which is the workhorse for RNNs implemented on it, runs very slow on GPU. See [this issue](https://github.com/Theano/Theano/issues/1168). So if you are keen on GPUs with RNNs, may be you are better off trying TensorFlow, I am not aware of any CTC implementations there. Or try warp_ctc. But that is written in C++ and might be hard to tailor to your needs.
