### ISSUE TITLE
speech recognition

### ISSUE THREAD

**Issue by madhavsund** [rakeshvar/rnn_ctc#5]
whether rnn_ctc can be used for speech recognition

**Comment by rakeshvar** [comment]
yes. Read the reference book.

**Comment by madhavsund** [comment]
thanks a lot  .
I tried with digit speech corpus. My architecture is 
input dimension: 40
output : 25
(BDLSTM, {"nunits": 30}),
epoch :100
number of samples :3700

but only silence is fired always...I tried with recurrent model, the same problem.
what could be the reason ...

**Comment by rakeshvar** [comment]
I can look at it after a month. You can leave me with the details to the data etc.

**Comment by madhavsund** [comment]
Ok.I will send the data.
When I tried with Handwritten digit corpus i get good accuracy.
so my doubt is whether the input data range should be between 0 to 1 for speech corpus too

**Comment by rakeshvar** [comment]
Which hand written digit-corpus did you try on? 
Can you send the details of that too?

**Comment by madhavsund** [comment]
I tried on Mnist database  with sequence input.
After normalizing the speech corpus. it is working fine.
Thanks a lot....

**Comment by rakeshvar** [comment]
Good to know that. 
Can you give a link to the data here? Thanks.

**Comment by rakeshvar** [comment]
Here is a hand-written [sentences dataset](http://www.iam.unibe.ch/fki/databases/iam-handwriting-database).

**Comment by madhavsund** [comment]
thanks for pointing out...

I trained  speech

## TEST

Shown : [8, 22, 13, 20] 8 22 13 20
Seen  : [8, 22, 13, 20] 8 22 13 20

SoftMax Firings:
 0¦                                                                    ¦
 1¦                                                                   ¦
 2¦                                                                   ¦
 3¦                                                                   ¦
 4¦                                                                   ¦
 5¦                                                                   ¦
 6¦                                                                   ¦
 7¦                                                                   ¦
 8¦█                                                                  ¦
 9¦                                                                   ¦
10¦                                                                   ¦
11¦                                                                   ¦
12¦                                                                   ¦
13¦  █                                                                ¦
14¦                                                                   ¦
15¦                                                                   ¦
16¦                                                                   ¦
17¦                                                                   ¦
18¦                                                                   ¦
19¦                                                                   ¦
20¦   █                                                               ¦
21¦                                                                   ¦
22¦ █                                                                 ¦
23¦                                                                   ¦
24¦                                                                   ¦
25¦    ███████████████████████████████████████████████████████████████¦

the output is correct but It is not firing with respect to time.
it outs the label in the starting itself
whether it is correct ???
I will share the data once it is fixed.

**Comment by rakeshvar** [comment]
@madhavsund 
It can not be so. There is something wrong with the rendering/copy-paste/print mechanism. A lot of spaces do not render well. You need to use ``` quoted  string while pasting on github.

Another possible explanation is that you are using a BDRNN.

**Comment by madhavsund** [comment]
yes i used BDLSTM .
I have attached the document containing output.

![screenshot from 2015-11-02 10 24 09](https://cloud.githubusercontent.com/assets/14866815/10874496/9d723926-814b-11e5-902e-ca836f7671bf.png)

**Comment by rakeshvar** [comment]
Bidirectional will do that. I am happy to know that BDLSTM is working so well. 
If you do not want such behaviour you can try just LSTM.

**Comment by madhavsund** [comment]
previously data was normalized between 0 to 1
but when i used the same network (BDLSTM) and normalized the data using Zscore( zero mean and unit variance)
I get output with respect to time...I am confused which one is correct

![screenshot from 2015-11-02 11 05 53](https://cloud.githubusercontent.com/assets/14866815/10874892/9fe86300-8151-11e5-8c4b-5ba017ef25bb.png)

**Comment by madhavsund** [comment]
kindly guide me how could i save the network , so that i can test the new images / test images in live mode

**Comment by rakeshvar** [comment]
Can you give me a link to the data (my gmail is same as my github id), so that I can replicate the problem on my computer. I will get back to you when I know what exactly is happening.

**Comment by cxf739** [comment]
hi，I meet a problem that is the input param nDims，I want to train an text line image with labels, like : a boy is playing football
so,I want to know the right data format. thanks a lot.
